name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3
  
      - name: ğŸ“¦ Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§Ø² secret Ø¬Ø¯ÛŒØ¯
  
      - name: ğŸ³ Deploy with SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@185.79.97.38 << 'EOF'
            cd ~/epaal-frontend  # Ù…Ø³ÛŒØ± Ù¾Ø±ÙˆÚ˜Ù‡ Ø¬Ø¯ÛŒØ¯
            git pull origin main
            docker-compose -f docker-compose.evaam.yml down --remove-orphans
            docker-compose -f docker-compose.evaam.yml up --build -d
          EOF